<?php

namespace Database\Seeders;

use App\Models\SiteManager;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SiteManagerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        SiteManager::insert(
            [
                // settings start ------------------------------------------------------------------------------------
                [
                    'type' => 'settings',
                    'section' => 'google_client_credentials',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                // sidebar start ------------------------------------------------------------------------------------
                [
                    'type' => 'sidebar',
                    'section' => 'crm',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'clients',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'client_group',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'client_statement',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'suppliers',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'supplier_group',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'supplier_statement',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'accounts',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'account',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'account_balance',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'account_statement',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'receive',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'expense',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'personal_expense',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'daily_expense',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'transfer',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'profit',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'total_balance_report',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'loan',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'project',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'invoice',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'draft_invoice',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'invoice_return',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'asset_and_stock',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'raw_material',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'batch_product',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'products',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'product',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'product_group',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'warehouse',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'product_asset',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'product_color',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'product_size',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'product_brand',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'product_unit',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'product_barcode',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'purchase',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'invoice_wise_purchase',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'purchase_report',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'purchase_return',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'product_stock',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'sms',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'staff',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'branch',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'office_purchase',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'due_report',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'sales_report',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'sales_report_all',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'sales_report_daily',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'sales_report_customer_wise',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'sales_report_group_wise',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'sales_report_product_wise',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'sales_report_product_group_wise',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'deposit_report',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'deposit_report_category_wise',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'deposit_report_customer_wise',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'expense_report',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'expense_report_category_wise',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'expense_report_subcategory_wise',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'expense_report_supplier_payment',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'configuration',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'income_category',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'expense_category',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'shortcut_menu',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'payment_method',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'company_information',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'bank',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'sidebar',
                    'section' => 'settings',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'client',
                    'section' => 'client_balance_adjustment',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'client',
                    'section' => 'remaining_due_date',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'supplier',
                    'section' => 'remaining_due_date',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'supplier',
                    'section' => 'cheque_schedule',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'dashboard',
                    'section' => 'total_client_previous_due',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'dashboard',
                    'section' => 'total_client_due',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'dashboard',
                    'section' => 'total_client_advance',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'dashboard',
                    'section' => 'total_return',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'dashboard',
                    'section' => 'backup',
                    'status' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'dashboard',
                    'section' => 'server_info',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'dashboard',
                    'section' => 'yearly_calculation',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'dashboard',
                    'section' => 'monthly_calculation',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'type' => 'dashboard',
                    'section' => 'daily_calculation',
                    'status' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                // sidebar end --------------------------------------------------------------------------------------
            ]
        );
    }
}
